### ISSUE TITLE
I have a repo for the E490 aswell

### ISSUE THREAD

**Issue by jamieernest** [jubarim/Hackintosh-Lenovo-E490#2]
I'm not sure how to contact you but you should give my E490 repo a try. I have all features working except for DRM and HDMI. My repo is [Lenovo-E490-Hackintosh](https://github.com/jamieernest/lenovo-e490-hackintosh)

**Comment by jubarim** [comment]
Hi Jamie! Thanks very much for letting me know :-) 
I was about to give up in this E490... 
I will try your repo next weekend and let you know.

**Comment by jamieernest** [comment]
No problem :)
